default: &default
  adapter: postgresql
  pool: 5 
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: hitw-development

test:
  <<: *default
  database: hitw-test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>