development:
  adapter: postgresql
  encoding: unicode
  database: hole-in-the-wall_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: hole-in-the-wall_test
  host: localhost
  pool: 5
  timeout: 5000