default: &default
  adapter: sqlite3
  pool: 5 
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: pg
  database: hole-in-the-wall-production